blueprint:
  name: Fully Charge Battery Once a Week
  description: Charges battery to 100 % if wasn't charged during last week 
  domain: automation
  input:
    time:
      name: Time
      description: Time of start battery charging
      selector:
        time:
    production_forecast:
      name: Production Forecast
      description: Forecast of today's production
      selector:
        entity:
          filter:
            domain: sensor
    goodwe_power:
      name: GoodWe Charging Power
      description: The target entity describing power of eco charging mode
      selector:
        target:
          entity:
            domain: number
            integration: goodwe
    goodwe_final_soc:
      name: GoodWe Final SoC Entity
      description: The target entity describing final value of battery charging
      selector:
        target:
          entity:
            domain: number
            integration: goodwe
    goodwe_mode:
      name: GoodWe Mode
      description: Entity describing mode of the inverter
      selector:
        target:
          entity:
            domain: select
            integration: goodwe
    goodwe_actual_soc:
      name: GoodWe SoC Sensor
      description: GoodWe actual state of charge sensor
      selector:
        entity:
          filter:
            domain: sensor
            integration: goodwe

triggers:
  - trigger: time
    at: !input time
conditions:
  - condition: state
    entity_id: binary_sensor.battery_was_fully_charged_in_last_week
    state: 'off'
  - condition: numeric_state
    entity_id: !input production_forecast
    below: input_number.threshold_for_changing_dod
  - condition: state
    entity_id: input_select.season
    state: Winter
variables:
  soc: !input goodwe_actual_soc
actions:
  - action: number.set_value
    target: !input goodwe_power
    data:
      value: 20
  - delay: 00:00:05
  - action: number.set_value
    target: !input goodwe_final_soc
    data:
      value: 100
  - delay: 00:00:05
  - action: select.select_option
    target: !input goodwe_mode
    data:
      option: eco_charge
  - sequence:
    - wait_template: '{{ states(soc) | float(default=0) > 99 }}'
    - action: select.select_option
      target: !input goodwe_mode
      data:
        option: general
mode: single
