blueprint:
  name: Disable Overflow
  description: 'Disables overflow when eletricity price is negative (Export Limit is set to 0). When the spot price is positive again, script sets Export Limit back to entered Value.'
  domain: automation
  input:
    spot_price:
      name: Energy Spot Price
      description: Actual energy spot price entity
      selector:
        entity:
          filter:
            domain: sensor
    goodwe_entity:
      name: Export Limit
      description: Inverter export limit target entity
      selector:
        target:
          entity:
            domain: number
            integration: goodwe
    limit_value:
      name: Export Limit Number
      description: Value of the original export limit (W)
      selector:
        number:
          min: 0
          max: 15000
          step: 100
          unit_of_measurement: W
          mode: slider

triggers:
  - trigger: numeric_state
    entity_id: !input spot_price
    below: 0
conditions: []
actions:
  - action: number.set_value
    target: !input goodwe_entity
    data:
      value: 0
  - action: script.allow_overflow_when_positive_price_again
    metadata: {}
    data:
      spot_price: !input spot_price
      goodwe_entity: !input goodwe_entity
      limit_value: !input limit_value
mode: single